/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidoNumeroRouteImport } from './routes/pedido.$numero'
import { Route as MesaNumeroRouteImport } from './routes/mesa.$numero'
import { Route as MenuCodigoRouteImport } from './routes/menu.$codigo'
import { Route as CardapioSlugRouteImport } from './routes/cardapio.$slug'
import { Route as CCodigoRouteImport } from './routes/c.$codigo'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMasterIndexRouteImport } from './routes/_authenticated/master.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as MesaNumeroPedidosRouteImport } from './routes/mesa.$numero.pedidos'
import { Route as AuthenticatedMasterSuporteRouteImport } from './routes/_authenticated/master.suporte'
import { Route as AuthenticatedMasterLogsRouteImport } from './routes/_authenticated/master.logs'
import { Route as AuthenticatedMasterLicencasRouteImport } from './routes/_authenticated/master.licencas'
import { Route as AuthenticatedMasterConfiguracoesRouteImport } from './routes/_authenticated/master.configuracoes'
import { Route as AuthenticatedMasterClientesRouteImport } from './routes/_authenticated/master.clientes'
import { Route as AuthenticatedMasterAssinaturasRouteImport } from './routes/_authenticated/master.assinaturas'
import { Route as AuthenticatedAdminVendasRouteImport } from './routes/_authenticated/admin.vendas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated/admin.suporte'
import { Route as AuthenticatedAdminQrcodesRouteImport } from './routes/_authenticated/admin.qrcodes'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminPdvRouteImport } from './routes/_authenticated/admin.pdv'
import { Route as AuthenticatedAdminMesasRouteImport } from './routes/_authenticated/admin.mesas'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin.estoque'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminCatalogoRouteImport } from './routes/_authenticated/admin.catalogo'
import { Route as AuthenticatedAdminCardapioPublicoRouteImport } from './routes/_authenticated/admin.cardapio-publico'
import { Route as AuthenticatedAdminCaixaRouteImport } from './routes/_authenticated/admin.caixa'
import { Route as AuthenticatedAdminConfiguracoesIndexRouteImport } from './routes/_authenticated/admin.configuracoes.index'
import { Route as AuthenticatedAdminConfiguracoesUsuariosRouteImport } from './routes/_authenticated/admin.configuracoes.usuarios'
import { Route as AuthenticatedAdminConfiguracoesSuporteRouteImport } from './routes/_authenticated/admin.configuracoes.suporte'
import { Route as AuthenticatedAdminConfiguracoesSegurancaRouteImport } from './routes/_authenticated/admin.configuracoes.seguranca'
import { Route as AuthenticatedAdminConfiguracoesPerfilRouteImport } from './routes/_authenticated/admin.configuracoes.perfil'
import { Route as AuthenticatedAdminConfiguracoesPdvRouteImport } from './routes/_authenticated/admin.configuracoes.pdv'
import { Route as AuthenticatedAdminConfiguracoesPagamentosRouteImport } from './routes/_authenticated/admin.configuracoes.pagamentos'
import { Route as AuthenticatedAdminConfiguracoesNotificacoesRouteImport } from './routes/_authenticated/admin.configuracoes.notificacoes'
import { Route as AuthenticatedAdminConfiguracoesIntegracoesRouteImport } from './routes/_authenticated/admin.configuracoes.integracoes'
import { Route as AuthenticatedAdminConfiguracoesFinanceiroRouteImport } from './routes/_authenticated/admin.configuracoes.financeiro'
import { Route as AuthenticatedAdminConfiguracoesEstoqueRouteImport } from './routes/_authenticated/admin.configuracoes.estoque'
import { Route as AuthenticatedAdminConfiguracoesEmpresaRouteImport } from './routes/_authenticated/admin.configuracoes.empresa'
import { Route as AuthenticatedAdminConfiguracoesDesignRouteImport } from './routes/_authenticated/admin.configuracoes.design'
import { Route as AuthenticatedAdminConfiguracoesDescontosRouteImport } from './routes/_authenticated/admin.configuracoes.descontos'
import { Route as AuthenticatedAdminConfiguracoesBackupRouteImport } from './routes/_authenticated/admin.configuracoes.backup'
import { Route as AuthenticatedAdminConfiguracoesAssinaturaRouteImport } from './routes/_authenticated/admin.configuracoes.assinatura'
import { Route as AuthenticatedAdminConfiguracoesAparenciaRouteImport } from './routes/_authenticated/admin.configuracoes.aparencia'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoNumeroRoute = PedidoNumeroRouteImport.update({
  id: '/pedido/$numero',
  path: '/pedido/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaNumeroRoute = MesaNumeroRouteImport.update({
  id: '/mesa/$numero',
  path: '/mesa/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuCodigoRoute = MenuCodigoRouteImport.update({
  id: '/menu/$codigo',
  path: '/menu/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioSlugRoute = CardapioSlugRouteImport.update({
  id: '/cardapio/$slug',
  path: '/cardapio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodigoRoute = CCodigoRouteImport.update({
  id: '/c/$codigo',
  path: '/c/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterIndexRoute =
  AuthenticatedMasterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const MesaNumeroPedidosRoute = MesaNumeroPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => MesaNumeroRoute,
} as any)
const AuthenticatedMasterSuporteRoute =
  AuthenticatedMasterSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterLogsRoute = AuthenticatedMasterLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedMasterRoute,
} as any)
const AuthenticatedMasterLicencasRoute =
  AuthenticatedMasterLicencasRouteImport.update({
    id: '/licencas',
    path: '/licencas',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterConfiguracoesRoute =
  AuthenticatedMasterConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterClientesRoute =
  AuthenticatedMasterClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterAssinaturasRoute =
  AuthenticatedMasterAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedAdminVendasRoute =
  AuthenticatedAdminVendasRouteImport.update({
    id: '/vendas',
    path: '/vendas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQrcodesRoute =
  AuthenticatedAdminQrcodesRouteImport.update({
    id: '/qrcodes',
    path: '/qrcodes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPdvRoute = AuthenticatedAdminPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMesasRoute = AuthenticatedAdminMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogoRoute =
  AuthenticatedAdminCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCardapioPublicoRoute =
  AuthenticatedAdminCardapioPublicoRouteImport.update({
    id: '/cardapio-publico',
    path: '/cardapio-publico',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCaixaRoute = AuthenticatedAdminCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminConfiguracoesIndexRoute =
  AuthenticatedAdminConfiguracoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesUsuariosRoute =
  AuthenticatedAdminConfiguracoesUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesSuporteRoute =
  AuthenticatedAdminConfiguracoesSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesSegurancaRoute =
  AuthenticatedAdminConfiguracoesSegurancaRouteImport.update({
    id: '/seguranca',
    path: '/seguranca',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesPerfilRoute =
  AuthenticatedAdminConfiguracoesPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesPdvRoute =
  AuthenticatedAdminConfiguracoesPdvRouteImport.update({
    id: '/pdv',
    path: '/pdv',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesPagamentosRoute =
  AuthenticatedAdminConfiguracoesPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesNotificacoesRoute =
  AuthenticatedAdminConfiguracoesNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesIntegracoesRoute =
  AuthenticatedAdminConfiguracoesIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesFinanceiroRoute =
  AuthenticatedAdminConfiguracoesFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesEstoqueRoute =
  AuthenticatedAdminConfiguracoesEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesEmpresaRoute =
  AuthenticatedAdminConfiguracoesEmpresaRouteImport.update({
    id: '/empresa',
    path: '/empresa',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesDesignRoute =
  AuthenticatedAdminConfiguracoesDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesDescontosRoute =
  AuthenticatedAdminConfiguracoesDescontosRouteImport.update({
    id: '/descontos',
    path: '/descontos',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesBackupRoute =
  AuthenticatedAdminConfiguracoesBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesAssinaturaRoute =
  AuthenticatedAdminConfiguracoesAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)
const AuthenticatedAdminConfiguracoesAparenciaRoute =
  AuthenticatedAdminConfiguracoesAparenciaRouteImport.update({
    id: '/aparencia',
    path: '/aparencia',
    getParentRoute: () => AuthenticatedAdminConfiguracoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/master': typeof AuthenticatedMasterRouteWithChildren
  '/c/$codigo': typeof CCodigoRoute
  '/cardapio/$slug': typeof CardapioSlugRoute
  '/menu/$codigo': typeof MenuCodigoRoute
  '/mesa/$numero': typeof MesaNumeroRouteWithChildren
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/admin/caixa': typeof AuthenticatedAdminCaixaRoute
  '/admin/cardapio-publico': typeof AuthenticatedAdminCardapioPublicoRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRouteWithChildren
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/mesas': typeof AuthenticatedAdminMesasRoute
  '/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/qrcodes': typeof AuthenticatedAdminQrcodesRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/master/assinaturas': typeof AuthenticatedMasterAssinaturasRoute
  '/master/clientes': typeof AuthenticatedMasterClientesRoute
  '/master/configuracoes': typeof AuthenticatedMasterConfiguracoesRoute
  '/master/licencas': typeof AuthenticatedMasterLicencasRoute
  '/master/logs': typeof AuthenticatedMasterLogsRoute
  '/master/suporte': typeof AuthenticatedMasterSuporteRoute
  '/mesa/$numero/pedidos': typeof MesaNumeroPedidosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/master/': typeof AuthenticatedMasterIndexRoute
  '/admin/configuracoes/aparencia': typeof AuthenticatedAdminConfiguracoesAparenciaRoute
  '/admin/configuracoes/assinatura': typeof AuthenticatedAdminConfiguracoesAssinaturaRoute
  '/admin/configuracoes/backup': typeof AuthenticatedAdminConfiguracoesBackupRoute
  '/admin/configuracoes/descontos': typeof AuthenticatedAdminConfiguracoesDescontosRoute
  '/admin/configuracoes/design': typeof AuthenticatedAdminConfiguracoesDesignRoute
  '/admin/configuracoes/empresa': typeof AuthenticatedAdminConfiguracoesEmpresaRoute
  '/admin/configuracoes/estoque': typeof AuthenticatedAdminConfiguracoesEstoqueRoute
  '/admin/configuracoes/financeiro': typeof AuthenticatedAdminConfiguracoesFinanceiroRoute
  '/admin/configuracoes/integracoes': typeof AuthenticatedAdminConfiguracoesIntegracoesRoute
  '/admin/configuracoes/notificacoes': typeof AuthenticatedAdminConfiguracoesNotificacoesRoute
  '/admin/configuracoes/pagamentos': typeof AuthenticatedAdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/pdv': typeof AuthenticatedAdminConfiguracoesPdvRoute
  '/admin/configuracoes/perfil': typeof AuthenticatedAdminConfiguracoesPerfilRoute
  '/admin/configuracoes/seguranca': typeof AuthenticatedAdminConfiguracoesSegurancaRoute
  '/admin/configuracoes/suporte': typeof AuthenticatedAdminConfiguracoesSuporteRoute
  '/admin/configuracoes/usuarios': typeof AuthenticatedAdminConfiguracoesUsuariosRoute
  '/admin/configuracoes/': typeof AuthenticatedAdminConfiguracoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/c/$codigo': typeof CCodigoRoute
  '/cardapio/$slug': typeof CardapioSlugRoute
  '/menu/$codigo': typeof MenuCodigoRoute
  '/mesa/$numero': typeof MesaNumeroRouteWithChildren
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/admin/caixa': typeof AuthenticatedAdminCaixaRoute
  '/admin/cardapio-publico': typeof AuthenticatedAdminCardapioPublicoRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/mesas': typeof AuthenticatedAdminMesasRoute
  '/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/qrcodes': typeof AuthenticatedAdminQrcodesRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/master/assinaturas': typeof AuthenticatedMasterAssinaturasRoute
  '/master/clientes': typeof AuthenticatedMasterClientesRoute
  '/master/configuracoes': typeof AuthenticatedMasterConfiguracoesRoute
  '/master/licencas': typeof AuthenticatedMasterLicencasRoute
  '/master/logs': typeof AuthenticatedMasterLogsRoute
  '/master/suporte': typeof AuthenticatedMasterSuporteRoute
  '/mesa/$numero/pedidos': typeof MesaNumeroPedidosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/master': typeof AuthenticatedMasterIndexRoute
  '/admin/configuracoes/aparencia': typeof AuthenticatedAdminConfiguracoesAparenciaRoute
  '/admin/configuracoes/assinatura': typeof AuthenticatedAdminConfiguracoesAssinaturaRoute
  '/admin/configuracoes/backup': typeof AuthenticatedAdminConfiguracoesBackupRoute
  '/admin/configuracoes/descontos': typeof AuthenticatedAdminConfiguracoesDescontosRoute
  '/admin/configuracoes/design': typeof AuthenticatedAdminConfiguracoesDesignRoute
  '/admin/configuracoes/empresa': typeof AuthenticatedAdminConfiguracoesEmpresaRoute
  '/admin/configuracoes/estoque': typeof AuthenticatedAdminConfiguracoesEstoqueRoute
  '/admin/configuracoes/financeiro': typeof AuthenticatedAdminConfiguracoesFinanceiroRoute
  '/admin/configuracoes/integracoes': typeof AuthenticatedAdminConfiguracoesIntegracoesRoute
  '/admin/configuracoes/notificacoes': typeof AuthenticatedAdminConfiguracoesNotificacoesRoute
  '/admin/configuracoes/pagamentos': typeof AuthenticatedAdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/pdv': typeof AuthenticatedAdminConfiguracoesPdvRoute
  '/admin/configuracoes/perfil': typeof AuthenticatedAdminConfiguracoesPerfilRoute
  '/admin/configuracoes/seguranca': typeof AuthenticatedAdminConfiguracoesSegurancaRoute
  '/admin/configuracoes/suporte': typeof AuthenticatedAdminConfiguracoesSuporteRoute
  '/admin/configuracoes/usuarios': typeof AuthenticatedAdminConfiguracoesUsuariosRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/master': typeof AuthenticatedMasterRouteWithChildren
  '/c/$codigo': typeof CCodigoRoute
  '/cardapio/$slug': typeof CardapioSlugRoute
  '/menu/$codigo': typeof MenuCodigoRoute
  '/mesa/$numero': typeof MesaNumeroRouteWithChildren
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/_authenticated/admin/caixa': typeof AuthenticatedAdminCaixaRoute
  '/_authenticated/admin/cardapio-publico': typeof AuthenticatedAdminCardapioPublicoRoute
  '/_authenticated/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRouteWithChildren
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/mesas': typeof AuthenticatedAdminMesasRoute
  '/_authenticated/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/qrcodes': typeof AuthenticatedAdminQrcodesRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/_authenticated/master/assinaturas': typeof AuthenticatedMasterAssinaturasRoute
  '/_authenticated/master/clientes': typeof AuthenticatedMasterClientesRoute
  '/_authenticated/master/configuracoes': typeof AuthenticatedMasterConfiguracoesRoute
  '/_authenticated/master/licencas': typeof AuthenticatedMasterLicencasRoute
  '/_authenticated/master/logs': typeof AuthenticatedMasterLogsRoute
  '/_authenticated/master/suporte': typeof AuthenticatedMasterSuporteRoute
  '/mesa/$numero/pedidos': typeof MesaNumeroPedidosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/master/': typeof AuthenticatedMasterIndexRoute
  '/_authenticated/admin/configuracoes/aparencia': typeof AuthenticatedAdminConfiguracoesAparenciaRoute
  '/_authenticated/admin/configuracoes/assinatura': typeof AuthenticatedAdminConfiguracoesAssinaturaRoute
  '/_authenticated/admin/configuracoes/backup': typeof AuthenticatedAdminConfiguracoesBackupRoute
  '/_authenticated/admin/configuracoes/descontos': typeof AuthenticatedAdminConfiguracoesDescontosRoute
  '/_authenticated/admin/configuracoes/design': typeof AuthenticatedAdminConfiguracoesDesignRoute
  '/_authenticated/admin/configuracoes/empresa': typeof AuthenticatedAdminConfiguracoesEmpresaRoute
  '/_authenticated/admin/configuracoes/estoque': typeof AuthenticatedAdminConfiguracoesEstoqueRoute
  '/_authenticated/admin/configuracoes/financeiro': typeof AuthenticatedAdminConfiguracoesFinanceiroRoute
  '/_authenticated/admin/configuracoes/integracoes': typeof AuthenticatedAdminConfiguracoesIntegracoesRoute
  '/_authenticated/admin/configuracoes/notificacoes': typeof AuthenticatedAdminConfiguracoesNotificacoesRoute
  '/_authenticated/admin/configuracoes/pagamentos': typeof AuthenticatedAdminConfiguracoesPagamentosRoute
  '/_authenticated/admin/configuracoes/pdv': typeof AuthenticatedAdminConfiguracoesPdvRoute
  '/_authenticated/admin/configuracoes/perfil': typeof AuthenticatedAdminConfiguracoesPerfilRoute
  '/_authenticated/admin/configuracoes/seguranca': typeof AuthenticatedAdminConfiguracoesSegurancaRoute
  '/_authenticated/admin/configuracoes/suporte': typeof AuthenticatedAdminConfiguracoesSuporteRoute
  '/_authenticated/admin/configuracoes/usuarios': typeof AuthenticatedAdminConfiguracoesUsuariosRoute
  '/_authenticated/admin/configuracoes/': typeof AuthenticatedAdminConfiguracoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/master'
    | '/c/$codigo'
    | '/cardapio/$slug'
    | '/menu/$codigo'
    | '/mesa/$numero'
    | '/pedido/$numero'
    | '/admin/caixa'
    | '/admin/cardapio-publico'
    | '/admin/catalogo'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/mesas'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/qrcodes'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/admin/vendas'
    | '/master/assinaturas'
    | '/master/clientes'
    | '/master/configuracoes'
    | '/master/licencas'
    | '/master/logs'
    | '/master/suporte'
    | '/mesa/$numero/pedidos'
    | '/admin/'
    | '/master/'
    | '/admin/configuracoes/aparencia'
    | '/admin/configuracoes/assinatura'
    | '/admin/configuracoes/backup'
    | '/admin/configuracoes/descontos'
    | '/admin/configuracoes/design'
    | '/admin/configuracoes/empresa'
    | '/admin/configuracoes/estoque'
    | '/admin/configuracoes/financeiro'
    | '/admin/configuracoes/integracoes'
    | '/admin/configuracoes/notificacoes'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/pdv'
    | '/admin/configuracoes/perfil'
    | '/admin/configuracoes/seguranca'
    | '/admin/configuracoes/suporte'
    | '/admin/configuracoes/usuarios'
    | '/admin/configuracoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/reset-password'
    | '/sitemap.xml'
    | '/c/$codigo'
    | '/cardapio/$slug'
    | '/menu/$codigo'
    | '/mesa/$numero'
    | '/pedido/$numero'
    | '/admin/caixa'
    | '/admin/cardapio-publico'
    | '/admin/catalogo'
    | '/admin/estoque'
    | '/admin/mesas'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/qrcodes'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/admin/vendas'
    | '/master/assinaturas'
    | '/master/clientes'
    | '/master/configuracoes'
    | '/master/licencas'
    | '/master/logs'
    | '/master/suporte'
    | '/mesa/$numero/pedidos'
    | '/admin'
    | '/master'
    | '/admin/configuracoes/aparencia'
    | '/admin/configuracoes/assinatura'
    | '/admin/configuracoes/backup'
    | '/admin/configuracoes/descontos'
    | '/admin/configuracoes/design'
    | '/admin/configuracoes/empresa'
    | '/admin/configuracoes/estoque'
    | '/admin/configuracoes/financeiro'
    | '/admin/configuracoes/integracoes'
    | '/admin/configuracoes/notificacoes'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/pdv'
    | '/admin/configuracoes/perfil'
    | '/admin/configuracoes/seguranca'
    | '/admin/configuracoes/suporte'
    | '/admin/configuracoes/usuarios'
    | '/admin/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/master'
    | '/c/$codigo'
    | '/cardapio/$slug'
    | '/menu/$codigo'
    | '/mesa/$numero'
    | '/pedido/$numero'
    | '/_authenticated/admin/caixa'
    | '/_authenticated/admin/cardapio-publico'
    | '/_authenticated/admin/catalogo'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/mesas'
    | '/_authenticated/admin/pdv'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/qrcodes'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/vendas'
    | '/_authenticated/master/assinaturas'
    | '/_authenticated/master/clientes'
    | '/_authenticated/master/configuracoes'
    | '/_authenticated/master/licencas'
    | '/_authenticated/master/logs'
    | '/_authenticated/master/suporte'
    | '/mesa/$numero/pedidos'
    | '/_authenticated/admin/'
    | '/_authenticated/master/'
    | '/_authenticated/admin/configuracoes/aparencia'
    | '/_authenticated/admin/configuracoes/assinatura'
    | '/_authenticated/admin/configuracoes/backup'
    | '/_authenticated/admin/configuracoes/descontos'
    | '/_authenticated/admin/configuracoes/design'
    | '/_authenticated/admin/configuracoes/empresa'
    | '/_authenticated/admin/configuracoes/estoque'
    | '/_authenticated/admin/configuracoes/financeiro'
    | '/_authenticated/admin/configuracoes/integracoes'
    | '/_authenticated/admin/configuracoes/notificacoes'
    | '/_authenticated/admin/configuracoes/pagamentos'
    | '/_authenticated/admin/configuracoes/pdv'
    | '/_authenticated/admin/configuracoes/perfil'
    | '/_authenticated/admin/configuracoes/seguranca'
    | '/_authenticated/admin/configuracoes/suporte'
    | '/_authenticated/admin/configuracoes/usuarios'
    | '/_authenticated/admin/configuracoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CCodigoRoute: typeof CCodigoRoute
  CardapioSlugRoute: typeof CardapioSlugRoute
  MenuCodigoRoute: typeof MenuCodigoRoute
  MesaNumeroRoute: typeof MesaNumeroRouteWithChildren
  PedidoNumeroRoute: typeof PedidoNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$numero': {
      id: '/pedido/$numero'
      path: '/pedido/$numero'
      fullPath: '/pedido/$numero'
      preLoaderRoute: typeof PedidoNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa/$numero': {
      id: '/mesa/$numero'
      path: '/mesa/$numero'
      fullPath: '/mesa/$numero'
      preLoaderRoute: typeof MesaNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$codigo': {
      id: '/menu/$codigo'
      path: '/menu/$codigo'
      fullPath: '/menu/$codigo'
      preLoaderRoute: typeof MenuCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio/$slug': {
      id: '/cardapio/$slug'
      path: '/cardapio/$slug'
      fullPath: '/cardapio/$slug'
      preLoaderRoute: typeof CardapioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$codigo': {
      id: '/c/$codigo'
      path: '/c/$codigo'
      fullPath: '/c/$codigo'
      preLoaderRoute: typeof CCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/': {
      id: '/_authenticated/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof AuthenticatedMasterIndexRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/mesa/$numero/pedidos': {
      id: '/mesa/$numero/pedidos'
      path: '/pedidos'
      fullPath: '/mesa/$numero/pedidos'
      preLoaderRoute: typeof MesaNumeroPedidosRouteImport
      parentRoute: typeof MesaNumeroRoute
    }
    '/_authenticated/master/suporte': {
      id: '/_authenticated/master/suporte'
      path: '/suporte'
      fullPath: '/master/suporte'
      preLoaderRoute: typeof AuthenticatedMasterSuporteRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/logs': {
      id: '/_authenticated/master/logs'
      path: '/logs'
      fullPath: '/master/logs'
      preLoaderRoute: typeof AuthenticatedMasterLogsRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/licencas': {
      id: '/_authenticated/master/licencas'
      path: '/licencas'
      fullPath: '/master/licencas'
      preLoaderRoute: typeof AuthenticatedMasterLicencasRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/configuracoes': {
      id: '/_authenticated/master/configuracoes'
      path: '/configuracoes'
      fullPath: '/master/configuracoes'
      preLoaderRoute: typeof AuthenticatedMasterConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/clientes': {
      id: '/_authenticated/master/clientes'
      path: '/clientes'
      fullPath: '/master/clientes'
      preLoaderRoute: typeof AuthenticatedMasterClientesRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/assinaturas': {
      id: '/_authenticated/master/assinaturas'
      path: '/assinaturas'
      fullPath: '/master/assinaturas'
      preLoaderRoute: typeof AuthenticatedMasterAssinaturasRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/admin/vendas': {
      id: '/_authenticated/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AuthenticatedAdminVendasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/qrcodes': {
      id: '/_authenticated/admin/qrcodes'
      path: '/qrcodes'
      fullPath: '/admin/qrcodes'
      preLoaderRoute: typeof AuthenticatedAdminQrcodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pdv': {
      id: '/_authenticated/admin/pdv'
      path: '/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AuthenticatedAdminPdvRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mesas': {
      id: '/_authenticated/admin/mesas'
      path: '/mesas'
      fullPath: '/admin/mesas'
      preLoaderRoute: typeof AuthenticatedAdminMesasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalogo': {
      id: '/_authenticated/admin/catalogo'
      path: '/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cardapio-publico': {
      id: '/_authenticated/admin/cardapio-publico'
      path: '/cardapio-publico'
      fullPath: '/admin/cardapio-publico'
      preLoaderRoute: typeof AuthenticatedAdminCardapioPublicoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/caixa': {
      id: '/_authenticated/admin/caixa'
      path: '/caixa'
      fullPath: '/admin/caixa'
      preLoaderRoute: typeof AuthenticatedAdminCaixaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes/': {
      id: '/_authenticated/admin/configuracoes/'
      path: '/'
      fullPath: '/admin/configuracoes/'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/usuarios': {
      id: '/_authenticated/admin/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/admin/configuracoes/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/suporte': {
      id: '/_authenticated/admin/configuracoes/suporte'
      path: '/suporte'
      fullPath: '/admin/configuracoes/suporte'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesSuporteRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/seguranca': {
      id: '/_authenticated/admin/configuracoes/seguranca'
      path: '/seguranca'
      fullPath: '/admin/configuracoes/seguranca'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesSegurancaRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/perfil': {
      id: '/_authenticated/admin/configuracoes/perfil'
      path: '/perfil'
      fullPath: '/admin/configuracoes/perfil'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesPerfilRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/pdv': {
      id: '/_authenticated/admin/configuracoes/pdv'
      path: '/pdv'
      fullPath: '/admin/configuracoes/pdv'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesPdvRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/pagamentos': {
      id: '/_authenticated/admin/configuracoes/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/configuracoes/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesPagamentosRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/notificacoes': {
      id: '/_authenticated/admin/configuracoes/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/configuracoes/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/integracoes': {
      id: '/_authenticated/admin/configuracoes/integracoes'
      path: '/integracoes'
      fullPath: '/admin/configuracoes/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesIntegracoesRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/financeiro': {
      id: '/_authenticated/admin/configuracoes/financeiro'
      path: '/financeiro'
      fullPath: '/admin/configuracoes/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/estoque': {
      id: '/_authenticated/admin/configuracoes/estoque'
      path: '/estoque'
      fullPath: '/admin/configuracoes/estoque'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesEstoqueRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/empresa': {
      id: '/_authenticated/admin/configuracoes/empresa'
      path: '/empresa'
      fullPath: '/admin/configuracoes/empresa'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesEmpresaRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/design': {
      id: '/_authenticated/admin/configuracoes/design'
      path: '/design'
      fullPath: '/admin/configuracoes/design'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesDesignRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/descontos': {
      id: '/_authenticated/admin/configuracoes/descontos'
      path: '/descontos'
      fullPath: '/admin/configuracoes/descontos'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesDescontosRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/backup': {
      id: '/_authenticated/admin/configuracoes/backup'
      path: '/backup'
      fullPath: '/admin/configuracoes/backup'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesBackupRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/assinatura': {
      id: '/_authenticated/admin/configuracoes/assinatura'
      path: '/assinatura'
      fullPath: '/admin/configuracoes/assinatura'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesAssinaturaRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
    '/_authenticated/admin/configuracoes/aparencia': {
      id: '/_authenticated/admin/configuracoes/aparencia'
      path: '/aparencia'
      fullPath: '/admin/configuracoes/aparencia'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesAparenciaRouteImport
      parentRoute: typeof AuthenticatedAdminConfiguracoesRoute
    }
  }
}

interface AuthenticatedAdminConfiguracoesRouteChildren {
  AuthenticatedAdminConfiguracoesAparenciaRoute: typeof AuthenticatedAdminConfiguracoesAparenciaRoute
  AuthenticatedAdminConfiguracoesAssinaturaRoute: typeof AuthenticatedAdminConfiguracoesAssinaturaRoute
  AuthenticatedAdminConfiguracoesBackupRoute: typeof AuthenticatedAdminConfiguracoesBackupRoute
  AuthenticatedAdminConfiguracoesDescontosRoute: typeof AuthenticatedAdminConfiguracoesDescontosRoute
  AuthenticatedAdminConfiguracoesDesignRoute: typeof AuthenticatedAdminConfiguracoesDesignRoute
  AuthenticatedAdminConfiguracoesEmpresaRoute: typeof AuthenticatedAdminConfiguracoesEmpresaRoute
  AuthenticatedAdminConfiguracoesEstoqueRoute: typeof AuthenticatedAdminConfiguracoesEstoqueRoute
  AuthenticatedAdminConfiguracoesFinanceiroRoute: typeof AuthenticatedAdminConfiguracoesFinanceiroRoute
  AuthenticatedAdminConfiguracoesIntegracoesRoute: typeof AuthenticatedAdminConfiguracoesIntegracoesRoute
  AuthenticatedAdminConfiguracoesNotificacoesRoute: typeof AuthenticatedAdminConfiguracoesNotificacoesRoute
  AuthenticatedAdminConfiguracoesPagamentosRoute: typeof AuthenticatedAdminConfiguracoesPagamentosRoute
  AuthenticatedAdminConfiguracoesPdvRoute: typeof AuthenticatedAdminConfiguracoesPdvRoute
  AuthenticatedAdminConfiguracoesPerfilRoute: typeof AuthenticatedAdminConfiguracoesPerfilRoute
  AuthenticatedAdminConfiguracoesSegurancaRoute: typeof AuthenticatedAdminConfiguracoesSegurancaRoute
  AuthenticatedAdminConfiguracoesSuporteRoute: typeof AuthenticatedAdminConfiguracoesSuporteRoute
  AuthenticatedAdminConfiguracoesUsuariosRoute: typeof AuthenticatedAdminConfiguracoesUsuariosRoute
  AuthenticatedAdminConfiguracoesIndexRoute: typeof AuthenticatedAdminConfiguracoesIndexRoute
}

const AuthenticatedAdminConfiguracoesRouteChildren: AuthenticatedAdminConfiguracoesRouteChildren =
  {
    AuthenticatedAdminConfiguracoesAparenciaRoute:
      AuthenticatedAdminConfiguracoesAparenciaRoute,
    AuthenticatedAdminConfiguracoesAssinaturaRoute:
      AuthenticatedAdminConfiguracoesAssinaturaRoute,
    AuthenticatedAdminConfiguracoesBackupRoute:
      AuthenticatedAdminConfiguracoesBackupRoute,
    AuthenticatedAdminConfiguracoesDescontosRoute:
      AuthenticatedAdminConfiguracoesDescontosRoute,
    AuthenticatedAdminConfiguracoesDesignRoute:
      AuthenticatedAdminConfiguracoesDesignRoute,
    AuthenticatedAdminConfiguracoesEmpresaRoute:
      AuthenticatedAdminConfiguracoesEmpresaRoute,
    AuthenticatedAdminConfiguracoesEstoqueRoute:
      AuthenticatedAdminConfiguracoesEstoqueRoute,
    AuthenticatedAdminConfiguracoesFinanceiroRoute:
      AuthenticatedAdminConfiguracoesFinanceiroRoute,
    AuthenticatedAdminConfiguracoesIntegracoesRoute:
      AuthenticatedAdminConfiguracoesIntegracoesRoute,
    AuthenticatedAdminConfiguracoesNotificacoesRoute:
      AuthenticatedAdminConfiguracoesNotificacoesRoute,
    AuthenticatedAdminConfiguracoesPagamentosRoute:
      AuthenticatedAdminConfiguracoesPagamentosRoute,
    AuthenticatedAdminConfiguracoesPdvRoute:
      AuthenticatedAdminConfiguracoesPdvRoute,
    AuthenticatedAdminConfiguracoesPerfilRoute:
      AuthenticatedAdminConfiguracoesPerfilRoute,
    AuthenticatedAdminConfiguracoesSegurancaRoute:
      AuthenticatedAdminConfiguracoesSegurancaRoute,
    AuthenticatedAdminConfiguracoesSuporteRoute:
      AuthenticatedAdminConfiguracoesSuporteRoute,
    AuthenticatedAdminConfiguracoesUsuariosRoute:
      AuthenticatedAdminConfiguracoesUsuariosRoute,
    AuthenticatedAdminConfiguracoesIndexRoute:
      AuthenticatedAdminConfiguracoesIndexRoute,
  }

const AuthenticatedAdminConfiguracoesRouteWithChildren =
  AuthenticatedAdminConfiguracoesRoute._addFileChildren(
    AuthenticatedAdminConfiguracoesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCaixaRoute: typeof AuthenticatedAdminCaixaRoute
  AuthenticatedAdminCardapioPublicoRoute: typeof AuthenticatedAdminCardapioPublicoRoute
  AuthenticatedAdminCatalogoRoute: typeof AuthenticatedAdminCatalogoRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRouteWithChildren
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminMesasRoute: typeof AuthenticatedAdminMesasRoute
  AuthenticatedAdminPdvRoute: typeof AuthenticatedAdminPdvRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminQrcodesRoute: typeof AuthenticatedAdminQrcodesRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVendasRoute: typeof AuthenticatedAdminVendasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCaixaRoute: AuthenticatedAdminCaixaRoute,
  AuthenticatedAdminCardapioPublicoRoute:
    AuthenticatedAdminCardapioPublicoRoute,
  AuthenticatedAdminCatalogoRoute: AuthenticatedAdminCatalogoRoute,
  AuthenticatedAdminConfiguracoesRoute:
    AuthenticatedAdminConfiguracoesRouteWithChildren,
  AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
  AuthenticatedAdminMesasRoute: AuthenticatedAdminMesasRoute,
  AuthenticatedAdminPdvRoute: AuthenticatedAdminPdvRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminQrcodesRoute: AuthenticatedAdminQrcodesRoute,
  AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVendasRoute: AuthenticatedAdminVendasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMasterRouteChildren {
  AuthenticatedMasterAssinaturasRoute: typeof AuthenticatedMasterAssinaturasRoute
  AuthenticatedMasterClientesRoute: typeof AuthenticatedMasterClientesRoute
  AuthenticatedMasterConfiguracoesRoute: typeof AuthenticatedMasterConfiguracoesRoute
  AuthenticatedMasterLicencasRoute: typeof AuthenticatedMasterLicencasRoute
  AuthenticatedMasterLogsRoute: typeof AuthenticatedMasterLogsRoute
  AuthenticatedMasterSuporteRoute: typeof AuthenticatedMasterSuporteRoute
  AuthenticatedMasterIndexRoute: typeof AuthenticatedMasterIndexRoute
}

const AuthenticatedMasterRouteChildren: AuthenticatedMasterRouteChildren = {
  AuthenticatedMasterAssinaturasRoute: AuthenticatedMasterAssinaturasRoute,
  AuthenticatedMasterClientesRoute: AuthenticatedMasterClientesRoute,
  AuthenticatedMasterConfiguracoesRoute: AuthenticatedMasterConfiguracoesRoute,
  AuthenticatedMasterLicencasRoute: AuthenticatedMasterLicencasRoute,
  AuthenticatedMasterLogsRoute: AuthenticatedMasterLogsRoute,
  AuthenticatedMasterSuporteRoute: AuthenticatedMasterSuporteRoute,
  AuthenticatedMasterIndexRoute: AuthenticatedMasterIndexRoute,
}

const AuthenticatedMasterRouteWithChildren =
  AuthenticatedMasterRoute._addFileChildren(AuthenticatedMasterRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMasterRoute: AuthenticatedMasterRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MesaNumeroRouteChildren {
  MesaNumeroPedidosRoute: typeof MesaNumeroPedidosRoute
}

const MesaNumeroRouteChildren: MesaNumeroRouteChildren = {
  MesaNumeroPedidosRoute: MesaNumeroPedidosRoute,
}

const MesaNumeroRouteWithChildren = MesaNumeroRoute._addFileChildren(
  MesaNumeroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CCodigoRoute: CCodigoRoute,
  CardapioSlugRoute: CardapioSlugRoute,
  MenuCodigoRoute: MenuCodigoRoute,
  MesaNumeroRoute: MesaNumeroRouteWithChildren,
  PedidoNumeroRoute: PedidoNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
